server: "hub.lambdatest.com"
user: ""
key: ""

common_caps:
  "build": "capybara-lambdatest"
  "name": "single-Test"

browser_caps:
  -
    "browserName": "chrome"    
    "platformName": "Android"
    "deviceName": "Galaxy S8 Plus"
    # "browserName": "chrome"
    # "version": "latest"
    # "platform": "Windows 7"
